In [2]:
import pandas as pd
import numpy as np
import re

In [1]:
def doooo():
    listy = []
    n = np.zeros((1000, 1000))
    with open("puzzle3_input.txt") as file:
        for line in file:
            listy.append(re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', line.strip())[0])

        listy[0]
        for l in listy:
            x0 = int(l[1]) 
            y0 = int(l[2]) 
            x1 = x0 + int(l[3]) 
            y1 = y0 + int(l[4])
            n[y0:y1, x0:x1] +=1
        print(len(n[n>1]))
        for l in listy:
            x0 = int(l[1]) 
            y0 = int(l[2]) 
            x1 = x0 + int(l[3]) 
            y1 = y0 + int(l[4])
            if (n[y0:y1, x0:x1] == 1).all():
                print(l[0])

In [3]:
%load_ext line_profiler

In [6]:
%lprun -f doooo doooo()
        

Timer unit: 1e-06 s

Total time: 0.044968 s
File: <ipython-input-1-dc6138d79e74>
Function: doooo at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def doooo():
     2         1          4.0      4.0      0.0      listy = []
     3         1       1191.0   1191.0      2.6      n = np.zeros((1000, 1000))
     4         1        102.0    102.0      0.2      with open("puzzle3_input.txt") as file:
     5      1336       3636.0      2.7      8.1          for line in file:
     6      1335      13541.0     10.1     30.1              listy.append(re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', line.strip())[0])
     7                                           
     8         1          2.0      2.0      0.0          listy[0]
     9      1336       1511.0      1.1      3.4          for l in listy:
    10      1335       1773.0      1.3      3.9              x0 = int(l[1]) 
    11      1335       1442.0      1.1      3.

In [66]:

%%timeit
import pandas as pd
import numpy as np
import re
with open("puzzle3_input.txt") as f:
    listy = np.array(f.read().split())
#     n = np.zeros((1000, 1000))
    
#     for l in listy:
#         x0 = int(l[1]) 
#         y0 = int(l[2]) 
#         x1 = x0 + int(l[3]) 
#         y1 = y0 + int(l[4])
#         n[y0:y1, x0:x1] +=1


    
    
    

1.46 ms ± 32.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [36]:
b
listy[0]
for l in listy:
    x0 = int(l[1]) 
    y0 = int(l[2]) 
    x1 = x0 + int(l[3]) 
    y1 = y0 + int(l[4])
    n[y0:y1, x0:x1] +=1

    
    



NameError: name 'listy' is not defined

In [77]:
len(n[n>1])

110383

In [46]:
b

array(['#1 @ 100,366: 24x27', '#2 @ 726,271: 11x15',
       '#3 @ 343,814: 17x18', ..., '#1334 @ 435,778: 25x13',
       '#1335 @ 562,221: 12x16', ''], dtype='<U22')

In [92]:
t = np.zeros((8,8))


In [70]:
listt = ["#1, @ 1,3: 4x4", "#2, @ 3,1: 4x4", "#3 @ 5,5: 2x2"]
listt = [x[0] for x in (re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', s) for s in listt)]

In [93]:
for l in listt:
    x0 = int(l[1]) 
    y0 = int(l[2]) 
    x1 = x0 + int(l[3]) 
    y1 = y0 + int(l[4])
    print(f"inches from the left: {x0}")
    print(f"inches from the top: {y0}")
    print(f"inches across: {x1-x0}")
    print(f"inches down: {y1-y0}")
    print(f"rightmost edge: {x1}")
    print(f"lowest edge: {y1}")
    t[y0:y1, x0:x1] +=1
    
for l in listt:
    x0 = int(l[1]) 
    y0 = int(l[2]) 
    x1 = x0 + int(l[3]) 
    y1 = y0 + int(l[4])
    if (t[y0:y1, x0:x1] == 1).all():
        print(l[0])
    

inches from the left: 1
inches from the top: 3
inches across: 4
inches down: 4
rightmost edge: 5
lowest edge: 7
inches from the left: 3
inches from the top: 1
inches across: 4
inches down: 4
rightmost edge: 7
lowest edge: 5
inches from the left: 5
inches from the top: 5
inches across: 2
inches down: 2
rightmost edge: 7
lowest edge: 7
#3


In [89]:
t[y0:y1, x0:x1] == 1.0


array([[False, False],
       [False, False]])

In [76]:
len(t[t>1])

4

In [76]:
listt


[('#1,', '1', '3', '4', '4'),
 ('#2,', '3', '1', '4', '4'),
 ('#3', '5', '5', '2', '2')]

In [77]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [83]:
test = np.zeros((1000,1000,2))

In [87]:
test[0][0][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [81]:
np.zeros((1,2,2))

array([[[0., 0.],
        [0., 0.]]])