In [1]:
import pandas as pd
import numpy as np
import re

In [5]:
def doooo():
    listy = []
    # 1000 X 1000 numpy 2d array with all zeros
    n = np.zeros((1000, 1000))
    with open("puzzle3_input.txt") as file:
        for line in file:
            listy.append(re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', line.strip())[0])

        listy[0]
        for l in listy:
            x0 = int(l[1]) 
            y0 = int(l[2]) 
            x1 = x0 + int(l[3]) 
            y1 = y0 + int(l[4])
            n[y0:y1, x0:x1] +=1
        print(len(n[n>1]))
        for l in listy:
            x0 = int(l[1]) 
            y0 = int(l[2]) 
            x1 = x0 + int(l[3]) 
            y1 = y0 + int(l[4])
            if (n[y0:y1, x0:x1] == 1).all():
                print(l[0])

In [6]:
%%timeit
doooo()

110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
110383
#129
21 ms ± 1.07 ms per loop (me

In [77]:
len(n[n>1])

110383

In [46]:
b

array(['#1 @ 100,366: 24x27', '#2 @ 726,271: 11x15',
       '#3 @ 343,814: 17x18', ..., '#1334 @ 435,778: 25x13',
       '#1335 @ 562,221: 12x16', ''], dtype='<U22')

In [92]:
t = np.zeros((8,8))


In [70]:
listt = ["#1, @ 1,3: 4x4", "#2, @ 3,1: 4x4", "#3 @ 5,5: 2x2"]
listt = [x[0] for x in (re.findall(r'(#.*)\s@\s(\d+),(\d+):\s(\d+)x(\d+)', s) for s in listt)]

In [93]:
for l in listt:
    x0 = int(l[1]) 
    y0 = int(l[2]) 
    x1 = x0 + int(l[3]) 
    y1 = y0 + int(l[4])
    print(f"inches from the left: {x0}")
    print(f"inches from the top: {y0}")
    print(f"inches across: {x1-x0}")
    print(f"inches down: {y1-y0}")
    print(f"rightmost edge: {x1}")
    print(f"lowest edge: {y1}")
    t[y0:y1, x0:x1] +=1
    
for l in listt:
    x0 = int(l[1]) 
    y0 = int(l[2]) 
    x1 = x0 + int(l[3]) 
    y1 = y0 + int(l[4])
    if (t[y0:y1, x0:x1] == 1).all():
        print(l[0])
    

inches from the left: 1
inches from the top: 3
inches across: 4
inches down: 4
rightmost edge: 5
lowest edge: 7
inches from the left: 3
inches from the top: 1
inches across: 4
inches down: 4
rightmost edge: 7
lowest edge: 5
inches from the left: 5
inches from the top: 5
inches across: 2
inches down: 2
rightmost edge: 7
lowest edge: 7
#3


In [89]:
t[y0:y1, x0:x1] == 1.0


array([[False, False],
       [False, False]])

In [76]:
len(t[t>1])

4

In [76]:
listt


[('#1,', '1', '3', '4', '4'),
 ('#2,', '3', '1', '4', '4'),
 ('#3', '5', '5', '2', '2')]

In [77]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [83]:
test = np.zeros((1000,1000,2))

In [87]:
test[0][0][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [81]:
np.zeros((1,2,2))

array([[[0., 0.],
        [0., 0.]]])